language: python
python: "3.9"
sudo: false
cache: pip
install:
  - pip install --upgrade pip
  - export CRYPTOGRAPHY_DONT_BUILD_RUST=1
  - pip install poetry
  - poetry install -vv
# command to run tests
script:
- export SLACK_API_TOKEN="meh"
- export JENKINS_USER_API_TOKEN="blablabla"
- export JENKINS2_USER_API_TOKEN="yaddayaddayadda"
- export JENKINS_JOB_TOKEN="abc123XYZ"
- export GITHUB_TOKEN="MEH-123"
- export JIRA_API_TOKEN="blah-456"
- PYTHONPATH="./qabot" poetry run python3 -u -m unittest discover tests
