language: python
python: "3.9"
sudo: false
cache: pip
install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - echo $HOME
  - echo $POETRY_HOME
  - ls $HOME
  - source $HOME/.poetry/env
  - poetry install -vv
# command to run tests
script:
- export SLACK_API_TOKEN="meh"
- export JENKINS_USER_API_TOKEN="blablabla"
- export JENKINS2_USER_API_TOKEN="yaddayaddayadda"
- export JENKINS_JOB_TOKEN="abc123XYZ"
- export GITHUB_TOKEN="MEH-123"
- export JIRA_API_TOKEN="blah-456"
- PYTHONPATH="./qabot" poetry run python3 -u -m unittest discover tests
