apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: ""
  volumeName: anythingllm-storage-pv