name: CI

on:
    push:
    pull_request:
        types: [opened, reopened]

jobs:

  unit_test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -vv
    - name: List installed packages
      run: pip list
    - name: Run tests
      env:
        DEVELOPMENT: true
        SLACK_BOT_TOKEN: meh
        SLACK_APP_TOKEN: mmehh
        GITHUB_TOKEN: MEH-123
        JIRA_API_TOKEN: blah-456
      run: |
        poetry run python3 -u -m unittest discover tests

  image_build_push:
    name: Build Image and Push
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      USE_QUAY_ONLY: true
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}